---
- hosts: devopschallenge
  gather_facts: false
  tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: devopschallenge
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes

  vars:
    playbook_version: 0.1b

  roles:
  - packages
  - user
  - database
  - drupal
  - civicrm
  - ssl
  - backup

  post_tasks:
    - name: Editing_php cgi.fix_pathinfo
      lineinfile:
        path: /etc/php/7.1/fpm/php.ini
        regexp: '^cgi.fix_pathinfo'
        line: 'cgi.fix_pathinfo = 0'

    - name: Editing_php max_execution_time
      lineinfile:
        path: /etc/php/7.1/fpm/php.ini
        regexp: '^max_execution_time'
        line: 'max_execution_time = 180'

    - name: Editing_php max_input_time
      lineinfile:
        path: /etc/php/7.1/fpm/php.ini
        regexp: '^max_input_time'
        line: 'max_input_time = 60'

    - name: Editing_php memory_limit
      lineinfile:
        path: /etc/php/7.1/fpm/php.ini
        regexp: '^memory_limit'
        line: 'memory_limit = 256M'

    - name: Editing_php filesize
      lineinfile:
        path: /etc/php/7.1/fpm/php.ini
        regexp: '^upload_max_filesize'
        line: 'upload_max_filesize = 64M'

  handlers:
  - include: roles/handlers/main.yml
