---
- name: Creating user
  user:
    name: "{{ user.name }}"
    state: present
    createhome: yes

- name: Allowing added user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ user.name }} ALL=(ALL) NOPASSWD: ALL'

- name: Setting authorized ssh key taken from file
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ user.pub_key }}"
    state: present

