---
- name: Create Drupal DB
  mysql_db:
    name: drupal
    state: present
    login_user: root
    login_password: root123

- name: Create CiviCRM DB
  mysql_db:
    name: civicrm
    state: present
    login_user: root
    login_password: root123

- name: Create a new DB user to drupal and civicrm and give him all access
  mysql_user:
    name: admin
    password: admin123
    priv: '*.*:ALL,GRANT'
    state: present
    login_user: root
    login_password: root123
