---
# DB Backup cron job options.
backup_db_hour: "1"

# Backup cron job options.
backup_cron_job_state: present
backup_hour: "3"
backup_minute: "00"

# User under which backup jobs will run.
backup_user: root

# Path to where backups configuration will be stored.
backup_path: /home/ladis/backup
backup_config_path: /bkp/config

# Directories to back up. {{ backup_user }} must have read access to these dirs.
backup_directories:
  - /bkp
  - /var/www/html
  - /etc
